### PR TITLE
Print better tracebacks

### PR DESCRIPTION
**Pull request by JasonGross**
This might help with debugging https://github.com/cpitclaudel/alectryon/issues/37

Idk if this is the best way to do this, or if you want it at all, but it seems to work.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Thanks! Looks good to me; can you show an example of the improved message?

**Comment by cpitclaudel** [comment]
Oh, fancy, it includes argument values?!

**Comment by JasonGross** [comment]
Example at https://github.com/cpitclaudel/alectryon/issues/37#issuecomment-823576812, and, yep!  It includes argument values.  This makes things extremely verbose, though, so it's questionable whether or not you want this enabled by default.  (Perhaps even hide it behind `--traceback-verbose` or something.)

**Comment by cpitclaudel** [comment]
Finally merged, thank you.  I changed the implementation since catching all exceptions broke PDB

**Pull request merged**
